# Generated by Django 5.2.1 on 2025-05-18 15:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用戶名')),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真實姓名')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='暱稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='電子郵件')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='user/portrait', verbose_name='頭像')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住址')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='手機號碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_vendor', models.BooleanField(default=False, verbose_name='是否商家')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'indexes': [models.Index(fields=['email'], name='account_use_email_553b8f_idx')],
            },
        ),
    ]
