# Generated by Django 5.2 on 2025-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('short_description', models.TextField(blank=True, verbose_name='簡短描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='價格')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('image', models.FileField(upload_to='products/', verbose_name='圖片')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
